# Under the hood of Multiple Linear Regression (MLR)

## **Formulas used**

> ### Regression Equation
>
> $y = b_0 + \sum^{n}_{i=1}{b_i \times x_i} + e$
>
> - $b_0$: Intercept of regression model
> 
> - $x_i$: $i^{th}$ feature(or predictor) of model
> 
> - $b_i$: Regression coefficient of $x_i$
> 
> - e is the error (Sum of squared error)


#### In multiple linear regression the coefficients are calculated by matrices

> ### Regression coefficients matrix.
> 
> $b = (X^TX)^{-1}X^TY$
> 
> - X is design matrix.
> 
> - $X^T$ is transpose of the design matrix
> 
> - Y is the Response matrix
> 
> - b is the **Regression coefficients matrix**

_**Definitions**_:

Design matrix is matrix of predictor columns prepended by the constant column

A transpose matrix is an array or matrix created by interchanging the rows and columns of an original matrix. It is denoted by $A^T$.

The inverse of a matrix is another matrix that, when multiplied by the given matrix, produces the identity matrix(Matrices of 0s and 1s).

$A^{-1}=\frac{1}{\det(A)}\text{adj}(A)$

$AA^{-1}=A^{-1}A=I$






### Finding p values of regression coefficients involves calculating T-Statistic  

> ### T-static of regression coefficients
> 
> $\sum_{i=0}^{n}{T_i = \frac{b_i}{S_{bi}}}$
>
> - $S_{bi}$ : Standard error of the slope $b_i$
> 
> ### $S_{b_i}$ of regression of coefficients
> 
> $S_{bi} = \sqrt{MSE * (XX^T)^{-1}}$
>
> - MSE: Mean square error or average of sum of residual error
> 
> - $(XX^T)^{-1}$: Covariance matrix
>
> - **Diagonal of covariance matrices are non-negative(or whole numbers) corresponds to the standard error of slopes**
>
> ### To calculate MSE
>
> MSE = $\frac{SSE}{(n - k - 1)}$
>
> - SSE: Sum of squared errors or Sum of squared **Residuals** or Variance of each point from its regression point.
>
> - n: No of samples (rows in the dataset)
>
> - k: No of features (Not including intercept)
>
> ### To calculate SSE (Sum of squared Residuals)
>
> SSE = $\sum_{i=0}^{n}{(y_i - \hat{y_i})}$
>
> - $y_i$ each ith(each) data point in the response variable
> 
> - $\hat{y_i}$ is the predicted value of $y_i$ obtained by substituting $x_i$ and $b_i$ in regression equation.




P values considering hypothesis testing 

$H_0$ : Population regression coefficient $(\beta)$ = 0 such that no linear relationship(as x varies y also varies)

$H_a$ : $\beta \ne 0$ suggesting as x varies y also varying

- Indicating Two tailed test from symbol of alternate hypothesis. 

- The difference in the p value of -b and b gives the total probability which tested against chosen significance level(say 0.05 or 5%). 




Example:

Say the t statistic of slope A is **-4.342** and degrees of freedom is 10

Need to find the probability associated with -4.342 and 10 DOF from t table or ``scipy.stats.t.cdf(-4.342,10)``which is the left tail(probability to the left). 

To find right tail one can just take ``1 - scipy.stats.t.cdf(4.342,10)``(probability to right) will give the right tail. To get p desired p value is ``scipy.stats.t.cdf(-4.342,10)`` + ``1 - scipy.stats.t.cdf(4.342,10)``

`scipy.stats.t.cdf(-4.342,10)` and `1 - scipy.stats.t.cdf(4.342,10)` will be same because the t-distribution is symmetrical.

Given the inference symmetrical, one can ``(1 - scipy.stats.t.cdf(abs(-4.342),10))*2``



```py
#Try
import scipy 
print(scipy.stats.t.cdf(-4.342,10) + (1- scipy.stats.t.cdf(4.342,10)),(1 - scipy.stats.t.cdf(abs(-4.342),10))*2)
```

> ### Calculation of $R^2$
> 
> $R^2 = 1 - \frac{SSE}{TSS}$
> 
> $R^2 = \frac{SSR}{TSS}$ 
>
> - TSS: Total sum of squares
> 
> - SSR: Sum of squares of Regression (or amount of variability in y explained by regression line)
>
> ### To calculate TSS
>
> $TSS = \sum_{i=0}^{n}{y_i - \bar{y}}$
>
> - $y_i$ is the ith data point of i and y is the mean of y. It explains the total variability of points explained by mean of y. (Worst case)
> 
> - $\bar{y}$ mean of y.
>
> ### To calculate the adjusted $R^2$
>
> $Adjusted \space R^2 = 1 - \frac{(n-2)(1 - R^2)}{n - k - 1}$
>
> - If any predictor in the model does not impact the model can addressed the adjacent r-squared
>
> - The adjusted R-squared value takes into account the number of predictors in the model and adjusts the R-squared value accordingly

Made with ❤️

---

Import statements

In [11]:
import numpy as np
import pandas as pd
from scipy.stats import t

Producing random matrices X and Y

In [12]:
np.random.seed(10)
X = np.random.randint(1,20,(100,2))
Y = np.random.randint(1,100,(100,1))

Adding constant of columns of 1 in order to get coefficient directly from design matrix and obtain results similar to OLS from Statsmodels and sklearn

In [13]:
X = np.insert(X,0,1,axis = 1)

$X^TX$

In [14]:
X_trans = np.transpose(X)
XX_trans = np.matmul(X_trans,X)
XX_trans

array([[  100,  1070,  1099],
       [ 1070, 14504, 12227],
       [ 1099, 12227, 14833]])

$(X^TX)^-1$

In [15]:
InvXX_trans = np.linalg.inv(XX_trans)
InvXX_trans

array([[ 8.00686697e-02, -2.96890812e-03, -3.48510945e-03],
       [-2.96890812e-03,  3.36066556e-04, -5.70522319e-05],
       [-3.48510945e-03, -5.70522319e-05,  3.72663178e-04]])

Information matrix 
 - $((X^TX)^-1)X^T$

In [16]:
InfoMat = np.matmul(InvXX_trans,X_trans)
InfoMat

array([[ 3.29540413e-02,  2.90810303e-02, -3.26185371e-02,
        -4.73766149e-03,  4.68944790e-02,  1.60446954e-02,
         5.97726853e-03,  9.46237797e-03,  2.62045890e-03,
         4.27648685e-02,  1.29474874e-02, -2.21632087e-02,
         1.34636887e-02, -6.80246679e-03,  5.67053062e-02,
        -2.51321168e-02,  6.10556835e-03, -5.38216264e-03,
        -3.55874452e-02,  1.44960914e-02, -2.56483182e-02,
         1.44960914e-02,  7.06457440e-02,  2.05622075e-02,
         3.73432535e-02, -2.16470074e-02,  3.97959603e-02,
        -1.62253925e-02,  8.17037364e-03,  5.58936702e-03,
        -1.57091912e-02,  1.43677916e-02, -1.27402830e-02,
         1.50122927e-02, -3.31735734e-03,  7.91377400e-03,
         7.13797099e-03,  2.94689318e-02,  1.08826821e-02,
         8.94617665e-03, -3.55874452e-02, -2.02267032e-02,
        -3.95887559e-02, -2.37118127e-02, -1.53212896e-02,
         1.43677916e-02, -8.86727208e-03,  5.07316570e-03,
        -3.90725546e-02, -3.26185371e-02,  5.61891049e-0

Regression matrix => info matrix x Y

In [17]:
regMatrix = np.matmul(InfoMat,Y)
regMatrix

array([[34.6176318 ],
       [ 0.74759158],
       [ 0.51893888]])

In regmatrix each row will map to each column. That is if first colum of design matrix A then first row of Y will be the regression coefficient of A, second row of Y will be the regression coffe of B and so on.. 

Changing the predictors columns will change the regression coefficients of according If B is the first column then the first row will be slope value  of B.  **Predictors does not have to follow an order**. Shuffling will not affect the coefficients

In [18]:
XFrame=pd.DataFrame(X)
XFrame.columns = ["Coff","A","B"]
XFrame

Coff   A   B
0      1  10   5
1      1  16   1
2      1  18  17
3      1  18   9
4      1  10   1
..   ...  ..  ..
95     1  11  10
96     1  13  17
97     1   5   7
98     1  10   9
99     1  17  12

[100 rows x 3 columns]

In [19]:
YFrame = pd.DataFrame(Y)
YFrame.columns = ["Y"]
YFrame

Y
0   40
1   59
2   82
3   40
4   50
..  ..
95  70
96  92
97  17
98   6
99  64

[100 rows x 1 columns]

Visualizing entire dataset

In [20]:
dfReg = pd.concat([XFrame,YFrame],axis=1)
dfReg

Coff   A   B   Y
0      1  10   5  40
1      1  16   1  59
2      1  18  17  82
3      1  18   9  40
4      1  10   1  50
..   ...  ..  ..  ..
95     1  11  10  70
96     1  13  17  92
97     1   5   7  17
98     1  10   9   6
99     1  17  12  64

[100 rows x 4 columns]

Declaring design matrix and Response matrix

In [21]:
X = dfReg.drop(columns=["Y"])
X

Coff   A   B
0      1  10   5
1      1  16   1
2      1  18  17
3      1  18   9
4      1  10   1
..   ...  ..  ..
95     1  11  10
96     1  13  17
97     1   5   7
98     1  10   9
99     1  17  12

[100 rows x 3 columns]

In [22]:
y = dfReg["Y"]
y

0     40
1     59
2     82
3     40
4     50
      ..
95    70
96    92
97    17
98     6
99    64
Name: Y, Length: 100, dtype: int32

Calculating the y prediction value (fitting regression line)

Ypred = X(with constant column)xb

In [23]:
y_pred = np.matmul(X,regMatrix)


SumOfSquaredError

In [24]:
SE = (Y - y_pred)**2
SE.columns = ["SE"]
SSE = SE["SE"].sum()
SSE

79047.53678295964

MSE = SSE/(n - k - 1)

Mean Square error or best error value that represent the whole SSE

In [25]:
n = len(Y) 
k = (len(X.columns)) - 1


MSE = SSE/(n - k - 1)

MSE

814.9230596181405

Total sum of squared error

In [26]:
Y_mean = dfReg["Y"].mean()

ST = (dfReg["Y"] - Y_mean)**2
SST = ST.sum()
SST

81859.76

R^2

In [27]:
R_sq = 1 - (SSE/SST)
R_sq

0.034354159076942836

SSR = Sum of squared by regression

In [28]:
SR =(y_pred - Y_mean)**2
SR.columns = ["SSR"]
SSR = SR["SSR"].sum()
SSR

2812.2232170403668

R^2 -> Measure of y explained by X or What is the percentage of Variance of Y is allocated to SSR and SSE

R^2 = By Introducing the variable X in Model how much of SST is allocated to SSR (Which says the percentage of Y is depended upon the X) and SSE (Percentage that was not dependend on X, need other features explain this)

In [29]:
SSR/SST

0.0343541590769429

Adjusted R^2

To take in the account of feature count. Adjusted R^2 is more trusted than R^2

In [30]:
Numerator2Term = (n - 1)*(1 - R_sq)
Adj_R_Sq = 1 - (Numerator2Term/(n - k - 1))
Adj_R_Sq

0.014443935552756026

BELOW TWO CELLS CALCULATES SB USING DIFFERENT FORMULAE

Formulae: sqrt((MSE*(1-R^2)/((n-k-1)*Variance of the Feature))

The above formulae is not used in OLS

Variance of features

In [31]:
Var_F = {i: np.round(X[i].var(),3) for i in (X.drop(columns=["Coff"])).columns}
    

Var_F

{'A': 30.859, 'B': 27.828}

Standard error of regression coefficient 

In [32]:
Num = np.round(MSE,3)*np.round((1 - R_sq),3)
Dem_1 = n - k - 1
St_b = {i:np.round(np.sqrt((Num/(Dem_1*Var_F[i]))),3) for i in Var_F}
St_b

{'A': 0.513, 'B': 0.54}

Formulae : sqrt(MSE*InvXX_trans)

is used to calculate SD_beta in OLS

In [33]:
dfReg.cov()

Coff          A          B           Y
Coff   0.0   0.000000   0.000000    0.000000
A      0.0  30.858586   4.724242   25.521212
B      0.0   4.724242  27.828182   17.972929
Y      0.0  25.521212  17.972929  826.866263

Covariance matrix and s_b calculation

In [34]:
CovMat = (MSE*InvXX_trans)
S_regCof_count = k + 1
s_b=[np.sqrt(CovMat[i][i]) for i in range(0,S_regCof_count)] #! standard error of slopes
s_b

[8.0777351590742, 0.5233243603366923, 0.5510824051344285]

T values

tb = b/s(b)

In [35]:
from scipy.stats import t

In [36]:
t_stastic = [regMatrix[ind][0]/i for ind,i in enumerate(s_b)]
t_stastic

[4.285561623264375, 1.4285434427629973, 0.9416720114011518]

P-Values

Cdf of t-distribution is governed by calculus. My implementation have not fit for computation, Using the ``scipy.stats.cdf and ..ppf`` 

In [37]:
p_values = [(1 - t.cdf(abs(i),n-k-1))*2 for i in t_stastic]
p_values

[4.2992412432774074e-05, 0.15634767795090276, 0.3486999153665822]

Verification

In [38]:
import statsmodels.api as sm

sm.OLS(Y,X).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.034
Model:                            OLS   Adj. R-squared:                  0.014
Method:                 Least Squares   F-statistic:                     1.725
Date:                Mon, 27 Feb 2023   Prob (F-statistic):              0.184
Time:                        12:11:11   Log-Likelihood:                -475.53
No. Observations:                 100   AIC:                             957.1
Df Residuals:                      97   BIC:                             964.9
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Coff          34.6176      8.078      4.286      0.000      18.586      50.650
A              0.7476      0.523      1.429      0.156      -0.291       1.786
B              0.5189      0.551      0.942      0.349      -0.575       1.613
==============================================================================
Omnibus:                       30.910   Durbin-Watson:                   2.249
Prob(Omnibus):                  0.000   Jarque-Bera (JB):                5.864
Skew:                          -0.053   Prob(JB):                       0.0533
Kurtosis:                       1.818   Cond. No.                         46.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [50]:


print(f"""

R-squared : {R_sq}

adj.R-squared: {Adj_R_Sq}

coef: ${regMatrix} 

std err: ${St_b} 

t: ${t_stastic}  

p: ${p_values}


""")



R-squared : 0.034354159076942836

adj.R-squared: 0.014443935552756026

coef: $[[34.6176318 ]
 [ 0.74759158]
 [ 0.51893888]] 

std err: ${'A': 0.513, 'B': 0.54} 

t: $[4.285561623264375, 1.4285434427629973, 0.9416720114011518]  

p: $[4.2992412432774074e-05, 0.15634767795090276, 0.3486999153665822]



